@url = https://8080-danisborges-api22025032-63bd6so56gw.ws-us118.gitpod.io

GET {{url}}/livros

###
GET {{url}}/livros/1

###
POST {{url}}/livros
Content-Type: application/json

{
    "titulo": "Novo Teste",
    "id_genero" : 1,
    "autores" : [{"id" : 1}]
}

###
PUT {{url}}/livros/5
Content-Type: application/json

{
    "titulo": "Livro 5 Alterado",
    "generos" : "Genero Alterado",
    "autores" : "Autor Alterado"
}

###
DELETE {{url}}/livros/5